# Generated by Django 4.1 on 2023-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_task_importance_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('Incomplete', '未完了'), ('Completed', '完了')], default='Incomplete', max_length=10),
        ),
    ]
